import {
  ClerkProvider
} from '@clerk/nextjs';
import { ReactLenis } from "lenis/react";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactLenis root>{children}</ReactLenis>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
