import { ClerkProvider } from "@clerk/nextjs";
import { ReactLenis } from "lenis/react";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "../globals.css";
import "@/models"; // Ensure models are registered

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <ReactLenis root>{children}</ReactLenis>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
